Implement Artificial Neural Network training process in Python by using Back
Propagation.

In [1]:
import numpy as np

In [2]:
# Define the parameters of the network
input_neuron = 2    # Number of input neurons
hidden_neuron = 4   # Number of hidden neurons
output_neuron = 1   # Number of output neurons
learning_rate = 0.1
epochs = 10000

In [3]:
# Define the training data
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
Y = np.array([[0], [1], [1], [0]])

In [4]:
# Initialize the weights and biases with random values
W1 = np.random.randn(input_neuron, hidden_neuron) * 0.01
W2 = np.random.randn(hidden_neuron, output_neuron) * 0.01
b1 = np.random.randn(1, hidden_neuron) * 0.01
b2 = np.random.randn(1, output_neuron) * 0.01

In [5]:
# Define the sigmoid activation function and its derivative
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [6]:
def sigmoid_derivative(x):
    return x * (1 - x)


In [7]:
# Perform backward propagation
for _ in range(epochs):
    # Forward pass
    hidden_layer_input = np.dot(X, W1) + b1
    hidden_layer_output = sigmoid(hidden_layer_input)
    output_layer_input = np.dot(hidden_layer_output, W2) + b2
    output_layer_output = sigmoid(output_layer_input)

    # Backward pass
    output_error = Y - output_layer_output
    output_delta = output_error * sigmoid_derivative(output_layer_output)
    hidden_error = output_delta.dot(W2.T)
    hidden_delta = hidden_error * sigmoid_derivative(hidden_layer_output)

    # Update weights and biases
    W2 += np.dot(hidden_layer_output.T, output_delta) * learning_rate
    b2 += np.sum(output_delta, axis=0, keepdims=True) * learning_rate
    W1 += np.dot(X.T, hidden_delta) * learning_rate
    b1 += np.sum(hidden_delta, axis=0, keepdims=True) * learning_rate

In [9]:
# Print the updated weights and biases
print("\nUpdated Weights W1:")
print(W1)
print("\nUpdated Weights W2:")
print(W2)
print("\nUpdated Biases b1:")
print(b1)
print("\nUpdated Biases b2:")
print(b2)



Updated Weights W1:
[[-0.00548237  0.0067269  -0.00458355  0.00105872]
 [ 0.00460103  0.01291279 -0.01661605  0.01234361]]

Updated Weights W2:
[[-0.00412703]
 [ 0.01010124]
 [-0.00417543]
 [ 0.00484588]]

Updated Biases b1:
[[-0.0028009  -0.0238991  -0.00267448 -0.00871664]]

Updated Biases b2:
[[-0.00330158]]
